export const GET_ROWS_FROM_SERVER = 'GET_ROWS_FROM_SERVER';
export const ADD_USER_IN_TABLE = 'ADD_USER_IN_TABLE';
export const SELECT_USER_IN_TABLE = 'SELECT_USER_IN_TABLE';
export const SWITCH_DATA_SIZE = 'SWITCH_DATA_SIZE';
export const SWITCH_DATA_LOADER = 'SWITCH_DATA_LOADER';
